### ISSUE TITLE
Add instructions to compile in static

### ISSUE THREAD

**Issue by macmonac** [ttys3/git-credential-readonly#2]
Hello,

Can you add instruction in Readme.md to compile the software manually and statically ?

```
CGO_ENABLED=0 go build
```

It's generate git-credential-readonly file that you can use on lot of differents version of Linux whatever the version of libc : https://mt165.co.uk/blog/static-link-go/

Regards
Pierre

**Comment by ttys3** [comment]
auto release CI has been added, could you please check https://github.com/ttys3/git-credential-readonly/releases/tag/v1.1.1

see the generated binaries OK?

**Comment by macmonac** [comment]
Hello,

It works s for me.

Regards
